<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>Idempotency.Api</AssemblyName>
    <RootNamespace>Idempotency</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="9.28.0" />
    <PackageReference Include="WolverineFx.Http" Version="6.29.0" />
    <PackageReference Include="WolverineFx.Http.Marten" Version="6.29.0" />
    <PackageReference Include="WolverineFx.Marten" Version="6.29.0" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.29.0" />
  </ItemGroup>

</Project>
